server:
    servlet:
        context-path: /api
    port: 8081
spring:
    application:
        name: meeting
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://<ip>:3306/meeting
        username: root
        password: <PASSWORD>
    data:
        redis:
            database: 0
            host: <ip>
            port: 6379
            password: <PASSWORD>
    profiles:
        active: prod

# springdoc-openapi配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        -   group: 'default'
            paths-to-match: '/**'
            packages-to-scan: org.lzg.meeting.controller
# knife4j增强配置
knife4j:
    enable: true
    setting:
        language: zh_cn
ws:
    port: 8082
#消息处理 可选redis或rabbitmq
message:
    handle:
        channel: redis